#!/bin/bash
#System Report generated
myuser=$USER
mydate=$(date +%A)


#system information
# gather data for our report
MYHOSTNAME=$(hostname)
OS=$(lsb_release -d | awk -F"\t" '{print $2}')
UPTIME=$(uptime -p)


# Gather hardware information
CPU_MODEL=$(cat /proc/cpuinfo | grep "model name" | uniq | awk -F": " '{print $2}')
### Use 'lscpu' command to extract the current CPU speed (in MHz) and assign it to the 'CPU_SPEED' variable
CPU_SPEED=$(lscpu | grep "MHz" | awk '{print $3}')
# Use the 'free' command to retrieve RAM information and assign the total size to 'RAM_SIZE' variable
RAM_SIZE=$(free -h | awk '/Mem/ {print $2}')
DISK_SPACE=$(df -h | awk '$NF=="/" {printf "Disk: %d/%dGB (%s)\n", $3, $2, $5}')
VIDEO_CARD=$(lspci | grep -i "VGA" | awk -F": " '{print $2}')



#Gather Network Information
# Function to get FQDN (Fully Qualified Domain Name)
FQDN=$(hostname -f)
# Function to get Host Address (IP address for the hostname)
HOSTNAME=$(hostname)
HOST_ADDRESS=$(getent ahosts "$HOSTNAME" | awk '{print $1}' | head -n1)
# Function to get Gateway IP
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')
# Function to get DNS Server IP
DNS_SERVER=$(nmcli dev show | grep 'IP4.DNS' | awk '{print $2}')
# Function to get Interface Name and IP Address in CIDR format
INTERFACE_NAME=$(ip -o link show | awk -F ': ' '{print $2}')
IP_ADDRESS=$(ip a show $INTERFACE | awk '/inet / {print $2}')

###System Status

# Get a list of users who are currently logged in
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
# Get disk space information 
DISK_SPACE=$(df -h | awk '/^\/dev/ {print $6" "$4}')
# Count the total number of running processes
PROCESS_COUNT=$(ps aux | wc -l)
# Get the load averages from the `uptime` command
LOAD_AVERAGES=$(uptime | awk -F'average: ' '{ print $2 }')
# Get memory allocation information  using the free command
MEMORY_ALLOCATION=$(free -h | awk 'NR==2 {print $3, $2}')
# Find listening network ports using the `ss` command
LISTENING_NETWORK=$(ss -tuln | awk '{print $5}' | cut -d ':' -f2 | grep -E "^[0-9]" | sort -n | uniq | tr '\n' ', ' | sed 's/,$//')
# Get UFW rules with numbers and actions using sudo ufw status numbered
UFW_RULES=$(sudo ufw status numbered | awk '{print $1" "$2" "$3}')

echo ""
echo "System Report generated by $(whoami), $(date)"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU_MODEL"
echo "Speed: $CPU_SPEED MHz"
echo "RAM: $RAM_SIZE"
echo "$DISK_SPACE"
echo "Video: $VIDEO_CARD"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_ADDRESS"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"
echo "Interface Name: $INTERFACE_NAME"
echo "IP Address: $IP_ADDRESS"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: ${USERS%,}"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "MEMORY_ALLOCATION: $MEMORY_ALLOCATION"
echo "Listening Network Ports: $LISTENING_NETWORK"
echo "UFW Rules: $UFW_RULES"
echo ""

# End of Report
